[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = ["@chainlink/contracts/=lib/chainlink-brownie-contracts/contracts/"]
ffi = true
# this means we can run commands directly on your machine
#this is the way to run bash scripts in foundry
# See https://docs.foundry.rs/manual/compiling-for-ffi.html
# here it is to ru the devopstools and get contractadress from the devops library




# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
